### Thinking1：高德地图中的路径规划原理是怎样的？
### answer：用Dijkstra算法得到最短路径，并转化成时间维度。行程中如遇到路障被清除的情况，模型会根据相关计算结果进行动态规划，实时更新“最佳”路线。

### Thinking2:football.gml数据集中，美国大学生足球联赛，包括115支球队，被分为12个联盟。为什么使用LPA标签  传播进行社区发现，只发现了11个社区？
### answer：12个联盟是静态属性；11个社区是动态属性。

### Thinking3:微博采用了类似FaceBook的EdgeRank算法，如果你给微博的信息流做设计，你会如何设计？
### answer：权重高低按：粉丝亲密度、内容质量、原创程度、用户画像等来区分。

In [1]:
#Action1：使用Python模拟下面的PageRank计算过程，求每个节点的影响力（迭代100次）
import numpy as np
a = np.array([[0, 0, 0, 1/3, 0, 0], 
              [1/4, 0, 0, 0, 1/2, 0],
              [0, 1, 0, 1/3, 1/2, 0],
              [1/4, 0, 0, 0, 0, 1],
              [1/4, 0, 1, 1/3, 0, 0],
              [1/4, 0, 0, 0, 0, 0]])

b = np.array([1/6, 1/6, 1/6, 1/6, 1/6, 1/6])
w = b

#使用简化模型
def work(a, w):
    for i in range(100):
        w = np.dot(a, w)
        print(w)
#使用随机模型
def random_work(a, w, n):
    d = 0.85
    for i in range(100):
        w = (1-d)/n + d*np.dot(a, w)
        print(w)

print('简单模型：')
work(a, w)
print('随机模型：')
random_work(a, w, 6)

简单模型：
[0.05555556 0.125      0.30555556 0.20833333 0.26388889 0.04166667]
[0.06944444 0.14583333 0.32638889 0.05555556 0.38888889 0.01388889]
[0.01851852 0.21180556 0.3587963  0.03125    0.36226852 0.01736111]
[0.01041667 0.18576389 0.40335648 0.02199074 0.37384259 0.00462963]
[0.00733025 0.18952546 0.38001543 0.0072338  0.4132909  0.00260417]
[0.00241127 0.20847801 0.39858218 0.00443673 0.38425926 0.00183256]
[0.00147891 0.19273245 0.40208655 0.00243538 0.4006639  0.00060282]
[8.11792695e-04 2.00701678e-01 3.93876190e-01 9.72543724e-04
 4.03268068e-01 3.69727366e-04]
[3.24181241e-04 2.01836982e-01 4.02659894e-01 5.72675540e-04
 3.94403319e-01 2.02948174e-04]
[1.90891847e-04 1.97282705e-01 3.99229534e-01 2.83993484e-04
 4.02931831e-01 8.10453104e-05]
[9.46644947e-05 2.01513638e-01 3.98843285e-01 1.28768272e-04
 3.99371921e-01 4.77229617e-05]
[4.29227573e-05 1.99709627e-01 4.01242522e-01 7.13890854e-05
 3.98909874e-01 2.36661237e-05]
[2.37963618e-05 1.99465667e-01 3.99188360e-01 3.43968

In [6]:
#Action2：使用TextRank对新闻进行关键词提取，及文章摘要输出。

# -*- coding: utf-8 -*-
import jieba
import jieba.analyse
import jieba.posseg as pseg


with open('./news_高考.txt', 'r', encoding='utf-8') as file:
    sentence = file.read()
    print(sentence)

# 获取分词
seg_list = jieba.cut(sentence, cut_all=False)
print(' '.join(seg_list))
# 获取分词和词性
words = pseg.cut(sentence)
for word, flag in words:
	print('%s, %s' % (word, flag))


# 通过TF-IDF获取关键词
keywords = jieba.analyse.extract_tags(sentence, topK=20, withWeight=True, allowPOS=('n','nr','ns'))
for item in keywords:
    print(item[0],item[1])
print('-'*100)

# 基于TextRank算法的关键词抽取
#keywords = jieba.analyse.extract_tags(sentence, topK=20, withWeight=True, allowPOS=('n','nr','ns'))
#keywords = jieba.analyse.textrank(sentence, topK=20, withWeight=True, allowPOS=('ns', 'n', 'vn', 'v')) 
keywords = jieba.analyse.textrank(sentence, topK=20, withWeight=True, allowPOS=('n', 'ns')) 
#keywords = jieba.analyse.textrank(sentence, topK=20, withWeight=True) 
print(keywords)
for item in keywords:
    print(item[0],item[1])

7月23日，在万般期待中，各地2020年高考录取分数线陆续公布，拿到分数后的考生们可谓有人欢喜有人愁。安徽省当天也公布了录取分数线，其中文理科一本分数线分别为541分和515分，二本分数线分别为499分和435分。那么被称为亚洲最大的“高考工厂”毛坦厂中学高考成绩怎样？图为毛坦厂中学教室午休的考生。
7月23日，毛坦厂中学所在的安徽六安市毛坦厂镇官方发布喜报称，根据网络查询，六安市毛坦厂中学、金安高级中学、金安中学补习班2020年高考再创佳绩，再传捷报，安徽籍考生（不含外省考生）本科达线人数10176人，其中600分以上600分以上290人，理科最高分674分，文科最高分608分。也就是在2020年高考中，高考镇有1万多人达到本科线，听起来多少有点让人吃惊，这个数字还不包括其他十几个省份在毛坦厂复读的数百名考生。图为高考镇放学盛大的场面。今年的高考很特殊，因为疫情课业停摆两个多月，随后高考推迟一个月才考试，而就在考试进行时，安徽歙县因为洪水语文和数学被延期考试，湖北黄梅的考生硬是蹚水去考场，而云南一地的考生，考试时还发生了地震。图为高考前，高考镇的卡点。毛坦厂镇因为高考而驰名，被称为“亚洲最大的高考工厂”，外媒曾称该镇是一座偏僻的单一产业城镇，出产的是应试机器，就像其他一些专门生产袜子或圣诞饰品的中国乡镇一样心无旁骛。毛坦厂镇今年参加高考的考生人数超过1.7万人，涉及全国十多个省份。图为考生在上晚自习。
据悉，毛坦厂镇面积只有3.5平方公里，人口不过万余人，从1999年后，毛坦厂中学借高考复读声名鹊起，每年都要吸引2万多学生和1万多陪读家长，整个小镇接近5万人。租房、生活、学习，众多学生和家长的到来，小镇的经济都围绕着“高考”在转。图为每天早晨，陪读家长在洗衣。在高考前，为了保障高考的顺利进行，高考镇实行了史上最严的“封锁”，在疫情开始之初，通往毛坦厂镇的所有道路都被切断，4月初，安徽省境内高三年级开始复课之后，因为外来复读学生较多，毛坦厂镇曾经短暂对外地家长和考生开放了几天，随之又实行严格管控，一直到7月5日考生离开高考镇时才解封。图为高考前，考生进入学校测量体温。也正是如此，今年的高考镇比往年低调了很多，连往年最热闹的送考节也没有举行，而是和其他所有普通学校一样，用几辆大巴将考生送到市区考试。图为往年的送考节。和衡水中学不一样，到高考镇来学习的都是普通考生，还有

In [4]:
#pip install textrank4zh

In [7]:
#-*- encoding:utf-8 -*-
from textrank4zh import TextRank4Keyword, TextRank4Sentence
import jieba


with open('./news_高考.txt', 'r', encoding='utf-8') as file:
    text = file.read()
    print(text)

# 输出关键词，设置文本小写，窗口为2
tr4w = TextRank4Keyword()
tr4w.analyze(text=text, lower=True, window=3)
print('关键词：')
for item in tr4w.get_keywords(20, word_min_len=2):
    print(item.word, item.weight)


# 输出重要的句子
tr4s = TextRank4Sentence()
tr4s.analyze(text=text, lower=True, source = 'all_filters')
print('摘要：')
# 重要性较高的三个句子
for item in tr4s.get_key_sentences(num=3):
	# index是语句在文本中位置，weight表示权重
    print(item.index, item.weight, item.sentence)

7月23日，在万般期待中，各地2020年高考录取分数线陆续公布，拿到分数后的考生们可谓有人欢喜有人愁。安徽省当天也公布了录取分数线，其中文理科一本分数线分别为541分和515分，二本分数线分别为499分和435分。那么被称为亚洲最大的“高考工厂”毛坦厂中学高考成绩怎样？图为毛坦厂中学教室午休的考生。
7月23日，毛坦厂中学所在的安徽六安市毛坦厂镇官方发布喜报称，根据网络查询，六安市毛坦厂中学、金安高级中学、金安中学补习班2020年高考再创佳绩，再传捷报，安徽籍考生（不含外省考生）本科达线人数10176人，其中600分以上600分以上290人，理科最高分674分，文科最高分608分。也就是在2020年高考中，高考镇有1万多人达到本科线，听起来多少有点让人吃惊，这个数字还不包括其他十几个省份在毛坦厂复读的数百名考生。图为高考镇放学盛大的场面。今年的高考很特殊，因为疫情课业停摆两个多月，随后高考推迟一个月才考试，而就在考试进行时，安徽歙县因为洪水语文和数学被延期考试，湖北黄梅的考生硬是蹚水去考场，而云南一地的考生，考试时还发生了地震。图为高考前，高考镇的卡点。毛坦厂镇因为高考而驰名，被称为“亚洲最大的高考工厂”，外媒曾称该镇是一座偏僻的单一产业城镇，出产的是应试机器，就像其他一些专门生产袜子或圣诞饰品的中国乡镇一样心无旁骛。毛坦厂镇今年参加高考的考生人数超过1.7万人，涉及全国十多个省份。图为考生在上晚自习。
据悉，毛坦厂镇面积只有3.5平方公里，人口不过万余人，从1999年后，毛坦厂中学借高考复读声名鹊起，每年都要吸引2万多学生和1万多陪读家长，整个小镇接近5万人。租房、生活、学习，众多学生和家长的到来，小镇的经济都围绕着“高考”在转。图为每天早晨，陪读家长在洗衣。在高考前，为了保障高考的顺利进行，高考镇实行了史上最严的“封锁”，在疫情开始之初，通往毛坦厂镇的所有道路都被切断，4月初，安徽省境内高三年级开始复课之后，因为外来复读学生较多，毛坦厂镇曾经短暂对外地家长和考生开放了几天，随之又实行严格管控，一直到7月5日考生离开高考镇时才解封。图为高考前，考生进入学校测量体温。也正是如此，今年的高考镇比往年低调了很多，连往年最热闹的送考节也没有举行，而是和其他所有普通学校一样，用几辆大巴将考生送到市区考试。图为往年的送考节。和衡水中学不一样，到高考镇来学习的都是普通考生，还有