### Thinking1：常用的文本分类方法都有哪些？
### answer：如SVM、朴素贝叶斯模型、RNN、GRU，LSTM等。

### Thinking2:RNN为什么会出现梯度消失？
### answer：因为tanh’ <= 1，训练过程大部分情况下tanh的导数是小于1的,如果Ws也在[0,1]之间，当T很大的时候,W                          在T时刻的梯度就接近于0，即梯度消失。

In [22]:
import torch
from torch import nn, optim
from model import TextRNN
import numpy as np

#数据文件设置
train_file = '/cnews/cnews.train.txt'
test_file = '/cnews/cnews.test.txt'
val_file = '/cnews/cnews.val.txt'
vocab_file = '/cnews/cnews.vocab.txt'

def train():
    model = TextRNN().cuda()
    Loss = nn.MultiLabelSoftMarginLoss()
    optimizer = optim.Adam(model.parameters(),lr=0.001)
    
    for epoch in range(1000):
        print('epoch=', epoch)
        for step,(x_batch, y_batch) in enumerate(train_loader):
            x = x_batch.cuda()
            y = y_batch.cuda()
            out = model(x)
            loss = Loss(out, y)
            print('Loss=', loss)
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
            accuracy = np.mean((torch.argmax(out, 1) == torch.argmax(y, 1)).cpu().numpy())
            print(accuracy)

In [23]:
#!pip install tensorflow-gpu==1.13.1
from cnews_loader import read_category,read_vocab, process_file
#获取文本的类别以及对应ID的字典
categories,cat_to_id = read_category()
#获取训练文本中所有出现的字，以及对应的ID
words, word_to_id = read_vocab('cnews.vocab.txt')
#获取字数
vocab_size = len(words)
print(vocab_size)

# 数据加载及分批
# 获取训练数据每个字的id和对应标签的one-hot形式
x_train, y_train = process_file('cnews.train.txt', word_to_id, cat_to_id, 600)
print('x_train=', x_train)
x_val, y_val = process_file('cnews.val.txt', word_to_id, cat_to_id, 600)

5000
x_train= [[1609  659   56 ...    9  311    3]
 [   2  101   16 ... 1168    3   24]
 [ 465  855  521 ...  116  136   85]
 ...
 [   0    0    0 ...  701   35    3]
 [ 360   73    2 ...  695  450    3]
 [   0    0    0 ... 1537  637   85]]


In [24]:
import torch.utils.data as Data
#设置GPU
cuda = torch.device('cuda')
x_train, y_train = torch.LongTensor(x_train), torch.Tensor(y_train)
x_val, y_val = torch.LongTensor(x_val), torch.Tensor(y_val)

train_dataset = Data.TensorDataset(x_train, y_train)
train_loader = Data.DataLoader(dataset=train_dataset, batch_size=1000, shuffle=True)
train()

epoch= 0
Loss= tensor(0.7345, device='cuda:0', grad_fn=<MeanBackward1>)


/home/ma-user/anaconda3/envs/Pytorch-1.0.0/lib/python3.6/site-packages/torch/nn/modules/container.py:92: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  input = module(input)


0.089
epoch= 1
Loss= tensor(0.7344, device='cuda:0', grad_fn=<MeanBackward1>)
0.101
epoch= 2
Loss= tensor(0.7343, device='cuda:0', grad_fn=<MeanBackward1>)
0.101
epoch= 3
Loss= tensor(0.7344, device='cuda:0', grad_fn=<MeanBackward1>)
0.119
epoch= 4
Loss= tensor(0.7343, device='cuda:0', grad_fn=<MeanBackward1>)
0.112
epoch= 5
Loss= tensor(0.7341, device='cuda:0', grad_fn=<MeanBackward1>)
0.148
epoch= 6
Loss= tensor(0.7341, device='cuda:0', grad_fn=<MeanBackward1>)
0.125
epoch= 7
Loss= tensor(0.7341, device='cuda:0', grad_fn=<MeanBackward1>)
0.142
epoch= 8
Loss= tensor(0.7338, device='cuda:0', grad_fn=<MeanBackward1>)
0.167
epoch= 9
Loss= tensor(0.7339, device='cuda:0', grad_fn=<MeanBackward1>)
0.159
epoch= 10
Loss= tensor(0.7335, device='cuda:0', grad_fn=<MeanBackward1>)
0.162
epoch= 11
Loss= tensor(0.7335, device='cuda:0', grad_fn=<MeanBackward1>)
0.168
epoch= 12
Loss= tensor(0.7332, device='cuda:0', grad_fn=<MeanBackward1>)
0.177
epoch= 13
Loss= tensor(0.7329, device='cuda:0', grad_fn